## **Module 2 | Class 4 Assignment: Pandas for Data Analysis**

### **Section 1 — Series and DataFrames (maps to lecture section “Series and DataFrames”)**

### **Task 1.1**

In [6]:
import pandas as pd
df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur"],
    "age":  [22, 28, 31],
    "city": ["Tashkent", "Samarkand", "Bukhara"]
})

df

    name  age       city
0    Ali   22   Tashkent
1   Zara   28  Samarkand
2  Jasur   31    Bukhara

In [4]:
df['age']
# df["age"] returns a Series, not a DataFrame.

0    22
1    28
2    31
Name: age, dtype: int64

In [14]:
df[["name", "age"]]
# df[["name", "age"]] returns a DataFrame (because I am selecting multiple columns).

    name  age
0    Ali   22
1   Zara   28
2  Jasur   31

In [12]:
# Print the index of df
print(df.index)

RangeIndex(start=0, stop=3, step=1)

### **Task 1.2**

In [15]:
new_data = pd.DataFrame({
    "name": ["Dilshod"],
    "age": [30],
    "city": ["Andijan"]
})

In [16]:
df = pd.concat([df, new_data], ignore_index=True)

In [17]:
df

      name  age       city
0      Ali   22   Tashkent
1     Zara   28  Samarkand
2    Jasur   31    Bukhara
3  Dilshod   30    Andijan

### **Section 2 — Loading and Exploring (maps to lecture section “Loading and Exploring”)**

### **Task 2.1**
Find any small public CSV (e.g., from Kaggle Datasets — Iris, Titanic, Tips, etc.). Load it:

In [29]:
import pandas as pd

url = "https://raw.githubusercontent.com/plotly/datasets/master/2014_apple_stock.csv"

df = pd.read_csv(url,parse_dates=["AAPL_x"])

df.head()

      AAPL_x     AAPL_y
0 2014-01-02  77.445395
1 2014-01-03  77.045575
2 2014-01-06  74.896972
3 2014-01-07  75.856461
4 2014-01-08  75.091947

In [28]:
# Second data
# #Load any small CSV. If you don't have one, use this built-in dataset:
# from sklearn.datasets import load_iris
# iris = load_iris(as_frame=True)
# df1 = iris.frame
# df1.head()

### **Task 2.2**
Run each of the five inspection commands from the lecture and write one sentence about what you
learned from each:

In [30]:
df.head()
# User can quickly see what the data looks like (date and stock price format).

      AAPL_x     AAPL_y
0 2014-01-02  77.445395
1 2014-01-03  77.045575
2 2014-01-06  74.896972
3 2014-01-07  75.856461
4 2014-01-08  75.091947

In [31]:
df.shape
#I know how many records (days) and features the dataset contains.

(240, 2)

In [32]:
df.info()
# I see the data types (date as datetime, price as numeric) and whether there are missing values.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL_x  240 non-null    datetime64[ns]
 1   AAPL_y  240 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 3.9 KB

In [33]:
df.describe()
# I understand the average stock price and how much it changes over time.

                    AAPL_x      AAPL_y
count                  240  240.000000
mean   2014-06-24 04:18:00   90.102612
min    2014-01-02 00:00:00   69.004708
25%    2014-03-30 06:00:00   75.892511
50%    2014-06-24 12:00:00   91.551777
75%    2014-09-18 06:00:00   99.627842
max    2014-12-12 00:00:00  118.798656
std                    NaN   13.315813

In [35]:
df.isna().sum()
# I check if there are any missing values that need cleaning.

AAPL_x    0
AAPL_y    0
dtype: int64

## **Section3** — Filtering, GroupBy, Merging (maps to lecture section “Filtering,GroupBy, Merging”

### **Task 3.1 — Selection**

In [36]:
# Second data
#Load any small CSV. If you don't have one, use this built-in dataset:
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)
df1 = iris.frame
df1.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [37]:
df1["sepal length (cm)"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [43]:
df1[["sepal length (cm)", "petal length (cm)"]]

     sepal length (cm)  petal length (cm)
0                  5.1                1.4
1                  4.9                1.4
2                  4.7                1.3
3                  4.6                1.5
4                  5.0                1.4
..                 ...                ...
145                6.7                5.2
146                6.3                5.0
147                6.5                5.2
148                6.2                5.4
149                5.9                5.1

[150 rows x 2 columns]

In [44]:
df1.loc[0].head(10)

sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
target               0.0
Name: 0, dtype: float64

In [45]:
df1.iloc[0]

sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
target               0.0
Name: 0, dtype: float64

### **Task 3.2 — Boolean filtering**

In [46]:
df1[(df1["sepal length (cm)"] > 5) & (df1["target"] == 0)]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
10,5.4,3.7,1.5,0.2,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0
20,5.4,3.4,1.7,0.2,0
21,5.1,3.7,1.5,0.4,0
23,5.1,3.3,1.7,0.5,0
27,5.2,3.5,1.5,0.2,0
28,5.2,3.4,1.4,0.2,0
31,5.4,3.4,1.5,0.4,0
32,5.2,4.1,1.5,0.1,0
33,5.5,4.2,1.4,0.2,0
36,5.5,3.5,1.3,0.2,0
39,5.1,3.4,1.5,0.2,0
44,5.1,3.8,1.9,0.4,0
46,5.1,3.8,1.6,0.2,0
48,5.3,3.7,1.5,0.2,0

In [47]:
df1[(df1["petal length (cm)"] < 2) | (df1["sepal width (cm)"] > 3.5)]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0
8,4.4,2.9,1.4,0.2,0
9,4.9,3.1,1.5,0.1,0
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0
20,5.4,3.4,1.7,0.2,0
21,5.1,3.7,1.5,0.4,0
22,4.6,3.6,1.0,0.2,0
23,5.1,3.3,1.7,0.5,0
24,4.8,3.4,1.9,0.2,0
25,5.0,3.0,1.6,0.2,0
26,5.0,3.4,1.6,0.4,0
27,5.2,3.5,1.5,0.2,0
28,5.2,3.4,1.4,0.2,0
29,4.7,3.2,1.6,0.2,0
30,4.8,3.1,1.6,0.2,0
31,5.4,3.4,1.5,0.4,0
32,5.2,4.1,1.5,0.1,0
33,5.5,4.2,1.4,0.2,0
34,4.9,3.1,1.5,0.2,0
35,5.0,3.2,1.2,0.2,0
36,5.5,3.5,1.3,0.2,0
37,4.9,3.6,1.4,0.1,0
38,4.4,3.0,1.3,0.2,0
39,5.1,3.4,1.5,0.2,0
40,5.0,3.5,1.3,0.3,0
41,4.5,2.3,1.3,0.3,0
42,4.4,3.2,1.3,0.2,0
43,5.0,3.5,1.6,0.6,0
44,5.1,3.8,1.9,0.4,0
45,4.8,3.0,1.4,0.3,0
46,5.1,3.8,1.6,0.2,0
47,4.6,3.2,1.4,0.2,0
48,5.3,3.7,1.5,0.2,0
49,5.0,3.3,1.4,0.2,0
109,7.2,3.6,6.1,2.5,2
117,7.7,3.8,6.7,2.2,2
131,7.9,3.8,6.4,2.0,2

### **Task 3.3 — GroupBy: split-apply-combine**

In [48]:
df1.groupby("target")["sepal length (cm)"].mean()
# Simple GroupBy pattern (mean)

target
0    5.006
1    5.936
2    6.588
Name: sepal length (cm), dtype: float64

In [50]:
df1.groupby("target").agg({
    "sepal length (cm)": "mean",
    "petal length (cm)": "count"
})

# GroupBy with .agg() (multiple calculations)

        sepal length (cm)  petal length (cm)
target
0                   5.006                 50
1                   5.936                 50
2                   6.588                 50

### **Task 3.4 — Merging**

In [53]:
lookup_df = pd.DataFrame({
    "target": [0, 1, 2],
    "species_name": ["setosa", "versicolor", "virginica"]
})

lookup_df
# We will use the Iris dataset (df1) and create a lookup table for target → species name

   target species_name
0       0       setosa
1       1   versicolor
2       2    virginica

In [55]:
merged_df = pd.merge(df1, lookup_df, on="target", how="left")

merged_df.head()
# Step 2: Merge with main DataFrame

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa